const $=s=>document.querySelector(s);let state=null,paused=false;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const r=await fetch(path,{headers:{'content-type':'application/json'},...options});if(!r.ok){let e;try{e=(await r.json()).detail}catch{}throw new Error(e||`${r.status} ${r.statusText}`)}return r.status===204?null:r.json()}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function statusOf(m){if(m.sender_id!==state.pm_id)return'incoming';const rs=m.recipients||[];if(rs.length&&rs.every(r=>r.processed_at))return'processed';if(rs.length&&rs.every(r=>r.received_at))return'received';return'sent'}
function render(){const targets=state.targets||[],statuses=Object.fromEntries((state.statuses||[]).map(x=>[x.id,x]));$('#targets').innerHTML=targets.map(t=>{const s=statuses[t.local_name]||t;return`<div class="rail-agent"><i class="dot ${esc(s.lifecycle)}"></i>${esc(t.local_name)}</div>`}).join('')||'<span class="meta">none</span>';const selected=$('#recipient').value;$('#recipient').innerHTML=targets.map(t=>`<option value="${esc(t.local_name)}">${esc(t.local_name)}</option>`).join('');if(targets.some(t=>t.local_name===selected))$('#recipient').value=selected;const att=state.attention||[];$('#attention-count').textContent=att.length||'';$('#attention').innerHTML=att.map(a=>`<article class="request ${a.reply_level}"><span class="badge">${a.reply_level==='r3'?'PM CONFIRM':a.reply_level==='r2'?'REVIEW':'INFO'}</span><div><strong>${esc(a.sender_name)}</strong> <small>#${a.seq}</small><div>${esc(a.body)}</div></div><button data-answer="${a.seq}" data-sender="${esc(a.sender_id)}">Answer</button></article>`).join('');const tl=$('#timeline'),nearBottom=tl.scrollHeight-tl.scrollTop-tl.clientHeight<80;tl.innerHTML=(state.timeline||[]).map(m=>{const recipients=(m.recipients||[]).map(r=>r.display_name).join(', ');const st=statusOf(m);return`<div class="message-row"><div class="route">#${m.seq}<br>${esc(m.sender_name)} → ${esc(recipients)}</div><div class="body">${esc(m.body)}</div><div class="status ${st}">${st}</div></div>`}).join('');if(nearBottom)tl.scrollTop=tl.scrollHeight;$('#agent-grid').innerHTML=(state.agents||[]).map(a=>`<article class="card"><div class="card-head"><div><span class="provider">${esc(a.provider)}</span><h3>${esc(a.local_name||a.title)}</h3></div><span class="meta">${esc(a.lifecycle)}</span></div><div class="path">${esc(a.cwd||'')}</div><div class="actions"><button data-focus="${esc(a.surface_id)}">Open terminal</button><button class="${a.connected?'danger':''}" data-toggle="${esc(a.surface_id)}">${a.connected?'Disconnect':'Connect'}</button></div></article>`).join('');$('#shared-list').innerHTML=(state.shared||[]).map(x=>`<div class="shared-row"><strong>${esc(x.key)}</strong><div class="shared-value">${esc(x.value)}</div><div><button data-edit="${esc(x.key)}">Edit</button> <button class="danger" data-delete="${esc(x.key)}">×</button></div></div>`).join('')||'<p>No shared values.</p>';$('#work-list').innerHTML=(state.work||[]).map(w=>`<article class="card"><div class="card-head"><div><span class="provider">${esc(w.agent_name)}</span><h3>${esc(w.title)}</h3></div><span>${esc(w.status)}</span></div><p>${esc(w.last_report||'No report')}</p><div class="work-meta"><span>${formatTime(w.elapsed_seconds)}</span><span>tokens ${w.token_usage??'unknown'}</span></div></article>`).join('')||'<p>No work reports.</p>'}
function formatTime(s=0){return [3600,60,1].map(n=>{const v=Math.floor(s/n);s%=n;return String(v).padStart(2,'0')}).join(':')}
async function refresh(){if(paused)return;try{state=await api('/api/state');render();$('#connection').textContent='connected';$('#connection').classList.add('ok')}catch(e){$('#connection').textContent='disconnected';$('#connection').classList.remove('ok');toast(e.message)}}
document.addEventListener('click',async e=>{const nav=e.target.closest('.nav');if(nav){document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));nav.classList.add('active');$('#'+nav.dataset.view).classList.add('active');return}try{if(e.target.dataset.answer){const body=prompt('Reply to approval request');if(body)await api('/api/messages',{method:'POST',body:JSON.stringify({recipient_ids:[e.target.dataset.sender],body,in_reply_to:Number(e.target.dataset.answer)})})}else if(e.target.dataset.focus)await api('/api/agents/action',{method:'POST',body:JSON.stringify({surface_id:e.target.dataset.focus,action:'focus'})});else if(e.target.dataset.toggle)await api('/api/agents/action',{method:'POST',body:JSON.stringify({surface_id:e.target.dataset.toggle,action:'toggle'})});else if(e.target.dataset.edit)openShared(e.target.dataset.edit);else if(e.target.dataset.delete&&confirm(`Delete ${e.target.dataset.delete}?`))await api('/api/shared/'+encodeURIComponent(e.target.dataset.delete),{method:'DELETE'});else return;await refresh()}catch(err){toast(err.message)}});
$('#composer').addEventListener('submit',async e=>{e.preventDefault();const body=$('#message').value.trim(),recipient_id=$('#recipient').value;if(!body||!recipient_id)return;try{await api('/api/messages',{method:'POST',body:JSON.stringify({recipient_ids:[recipient_id],body})});$('#message').value='';await refresh()}catch(err){toast(err.message)}});$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.metaKey||e.ctrlKey))$('#composer').requestSubmit()});
const dialog=$('#shared-dialog');function openShared(key=''){const item=(state.shared||[]).find(x=>x.key===key);$('#shared-key').value=key;$('#shared-key').disabled=!!key;$('#shared-value').value=item?.value||'';paused=true;dialog.showModal()}$('#add-shared').onclick=()=>openShared();$('#shared-cancel').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{paused=false});$('#shared-form').addEventListener('submit',async e=>{e.preventDefault();const key=$('#shared-key').value.trim(),value=$('#shared-value').value.trim();try{await api('/api/shared/'+encodeURIComponent(key),{method:'PUT',body:JSON.stringify({key,value})});dialog.close();await refresh()}catch(err){toast(err.message)}});
refresh();setInterval(refresh,1200);
